In [1]:
import pandas as pd
import numpy as np
import os
import sys
import re

In [43]:
def import_VCF4_to_pandas(vcf_file, sep='\t'):
    header_lines = 0
    with open(vcf_file) as f:
        first_line = f.readline().strip()
        next_line = f.readline().strip()
        while next_line.startswith("##"):
            header_lines = header_lines + 1
            #print(next_line)
            next_line = f.readline()
    
    if first_line.endswith('VCFv4.2'):
        
        #Use first line as header
        dataframe = pd.read_csv(vcf_file, sep=sep, skiprows=[header_lines], header=header_lines)
        sample = dataframe.columns[-1]
        #dataframe.DP = dataframe.DP.str.split('=').str[1]
        dataframe.rename(columns={sample:'sample'}, inplace=True)
        #dataframe[['GT', 'AD', 'DP', 'GQ', 'PL']] = dataframe['sample'].str.split(":", expand=True)
         
        for index in dataframe.index:
            info_fields = re.findall(r';*([a-zA-Z]{1,20})=', dataframe.loc[index,'INFO'])
            info_values = re.findall(r'-?\d+\.?\d*e?[+-]?\d{0,2}', dataframe.loc[index,'INFO'])
            
            format_fields = dataframe.loc[index,'FORMAT'].split(":")
            format_values = dataframe.loc[index,'sample'].split(":")
                                    
            for ifield, ivalue in zip(info_fields,info_values):
                dataframe.loc[index,ifield] = ivalue
                
            for ffield, fvalue in zip(format_fields,format_values):
                dataframe.loc[index,ffield] = fvalue
            if len(format_values[1].split(",")) != 2:
                print(format_values[1].split(","), index)
        #dataframe.rename(columns={'AF':'af'}, inplace=True)
        #dataframe[['REF_AD', 'ALT_AD']] = dataframe['AD'].str.split(",", expand=True)

                
            
        
        #dataframe[['Fref', 'Rref', 'Fsample', 'Rsample']] = dataframe['DP4'].str.split(',', expand=True)
        #dataframe[['DP', 'AF', 'SB','Fref', 'Rref', 'Fsample', 'Rsample']] = dataframe[['DP', 'AF', 'SB','Fref', 'Rref', 'Fsample', 'Rsample']].astype(float)
    else:
        print("This vcf file is not v4.2")
        sys.exit(1)
           
    return dataframe

In [44]:
df1 = import_VCF4_to_pandas(vcf2)
df1.head()

['0', '50', '14'] 490
['0', '19', '11'] 1132
['0', '10', '31'] 1791

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,sample,...,QD,ReadPosRankSum,SOR,GT,AD,GQ,PL,PGT,PID,PS
0,MTB_anc,371,.,C,T,59.60,QD2,AC=1;AF=0.500;AN=2;BaseQRankSum=-2.017e+00;DP=...,GT:AD:DP:GQ:PL,"0/1:75,10:85:67:67,0,2418",...,0.70,-2.648e+00,1.005,0/1,"75,10",67,"67,0,2418",NaN,NaN,NaN
1,MTB_anc,2532,.,C,T,977.03,PASS,AC=2;AF=1.00;AN=2;DP=30;ExcessHet=3.0103;FS=0....,GT:AD:DP:GQ:PL,"1/1:0,30:30:89:991,89,0",...,32.57,NaN,0.976,1/1,"0,30",89,"991,89,0",NaN,NaN,NaN
2,MTB_anc,9143,.,C,T,5466.03,PASS,AC=2;AF=1.00;AN=2;DP=148;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,148:148:99:5480,444,0",...,25.36,NaN,1.257,1/1,"0,148",99,"5480,444,0",NaN,NaN,NaN
3,MTB_anc,9304,.,A,G,38.60,QD2,AC=1;AF=0.500;AN=2;BaseQRankSum=-1.041e+00;DP=...,GT:AD:DP:GQ:PL,"0/1:156,17:173:46:46,0,5018",...,0.22,-1.171e+00,0.453,0/1,"156,17",46,"46,0,5018",NaN,NaN,NaN
4,MTB_anc,11370,.,C,T,161.60,QD2,AC=1;AF=0.500;AN=2;BaseQRankSum=-1.271e+00;DP=...,GT:AD:DP:GQ:PL,"0/1:101,16:117:99:169,0,3181",...,1.38,0.135,0.663,0/1,"101,16",99,"169,0,3181",NaN,NaN,NaN

In [19]:
df = import_VCF4_to_pandas(vcf)

In [20]:
vcf = "test/3mixed.snp.hf.vcf"
vcf2 = "test/2mixed.snp.hf.vcf"

In [22]:
df1.head()

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,sample,...,QD,ReadPosRankSum,SOR,GT,AD,GQ,PL,PGT,PID,PS
0,MTB_anc,371,.,C,T,59.60,QD2,AC=1;AF=0.500;AN=2;BaseQRankSum=-2.017e+00;DP=...,GT:AD:DP:GQ:PL,"0/1:75,10:85:67:67,0,2418",...,0.70,-2.648e+00,1.005,0/1,"75,10",67,"67,0,2418",NaN,NaN,NaN
1,MTB_anc,2532,.,C,T,977.03,PASS,AC=2;AF=1.00;AN=2;DP=30;ExcessHet=3.0103;FS=0....,GT:AD:DP:GQ:PL,"1/1:0,30:30:89:991,89,0",...,32.57,NaN,0.976,1/1,"0,30",89,"991,89,0",NaN,NaN,NaN
2,MTB_anc,9143,.,C,T,5466.03,PASS,AC=2;AF=1.00;AN=2;DP=148;ExcessHet=3.0103;FS=0...,GT:AD:DP:GQ:PL,"1/1:0,148:148:99:5480,444,0",...,25.36,NaN,1.257,1/1,"0,148",99,"5480,444,0",NaN,NaN,NaN
3,MTB_anc,9304,.,A,G,38.60,QD2,AC=1;AF=0.500;AN=2;BaseQRankSum=-1.041e+00;DP=...,GT:AD:DP:GQ:PL,"0/1:156,17:173:46:46,0,5018",...,0.22,-1.171e+00,0.453,0/1,"156,17",46,"46,0,5018",NaN,NaN,NaN
4,MTB_anc,11370,.,C,T,161.60,QD2,AC=1;AF=0.500;AN=2;BaseQRankSum=-1.271e+00;DP=...,GT:AD:DP:GQ:PL,"0/1:101,16:117:99:169,0,3181",...,1.38,0.135,0.663,0/1,"101,16",99,"169,0,3181",NaN,NaN,NaN

In [140]:
df.dtypes

#CHROM             object
POS                 int64
ID                 object
REF                object
ALT                object
QUAL              float64
FILTER             object
INFO               object
FORMAT             object
sample             object
AC                 object
AF                 object
AN                 object
BaseQRankSum       object
DP                 object
ExcessHet          object
FS                 object
MLEAC              object
MLEAF              object
MQ                 object
MQRankSum          object
QD                 object
ReadPosRankSum     object
SOR                object
GT                 object
AD                 object
GQ                 object
PL                 object
PGT                object
PID                object
PS                 object
dtype: object